# Change these first
owner: Gonchito # Your GitHub organization or username, where this repository lives
repo: VerifStatusPages # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Rd+ prod
    url: https://rdplus.rdigitales.com.ar/v2/loggin.aspx
  - name: Rd+ test
    url: https://rdplus.rdtest.com.ar:4433/v2/loggin.aspx
  - name: Administracion prod
    url: https://administracion.rdigitales.com.ar/login.aspx
  - name: Administracion test
    url: https://administracion.rdtest.com.ar:4433//login.aspx
  - name: Cc prod
    url: https://ccweb.rdigitales.com.ar/Index.aspx
  - name: Cc test
    url: https://ccweb.rdtest.com.ar:4433/Index.aspx
  - name: Institucional prod
    url: https://www.rdigitales.com.ar
  - name: Institucional test
    url: https://www.rdtest.com.ar:4433
  - name: qbe prod
    url: https://qbe.rdigitales.com.ar
  - name: qbe test
    url: https://qbe.rdtest.com.ar:4433
    
assignees:
    -Gonchito

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /VerifStatusPages
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Estado paginas RD
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Pagina para monitorear el estado de las paginas de RD.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

